apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: chunk-transfer-no-retry
spec:
  policies:
    retries:
      noRetries:
        policy: constant
        maxRetries: 0
        duration: 0s

  targets:
    apps:
      chunk-receiver:
        retry: noRetries
      file-generator:
        retry: noRetries

scopes:
- chunk-sender
- nginx
